
package ch.maxant.jca_demo.bookingsystem;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookingSystemWebServiceService", targetNamespace = "http://bookingsystem.jca_demo.maxant.ch/", wsdlLocation = "http://localhost:8080/GenericConnectorDemoBookingSystemWebservice/BookingSystemWebService?wsdl")
public class BookingSystemWebServiceService
    extends Service
{

    private final static URL BOOKINGSYSTEMWEBSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKINGSYSTEMWEBSERVICESERVICE_EXCEPTION;
    private final static QName BOOKINGSYSTEMWEBSERVICESERVICE_QNAME = new QName("http://bookingsystem.jca_demo.maxant.ch/", "BookingSystemWebServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/GenericConnectorDemoBookingSystemWebservice/BookingSystemWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKINGSYSTEMWEBSERVICESERVICE_WSDL_LOCATION = url;
        BOOKINGSYSTEMWEBSERVICESERVICE_EXCEPTION = e;
    }

    public BookingSystemWebServiceService() {
        super(__getWsdlLocation(), BOOKINGSYSTEMWEBSERVICESERVICE_QNAME);
    }

    public BookingSystemWebServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKINGSYSTEMWEBSERVICESERVICE_QNAME, features);
    }

    public BookingSystemWebServiceService(URL wsdlLocation) {
        super(wsdlLocation, BOOKINGSYSTEMWEBSERVICESERVICE_QNAME);
    }

    public BookingSystemWebServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKINGSYSTEMWEBSERVICESERVICE_QNAME, features);
    }

    public BookingSystemWebServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookingSystemWebServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookingSystem
     */
    @WebEndpoint(name = "BookingSystemPort")
    public BookingSystem getBookingSystemPort() {
        return super.getPort(new QName("http://bookingsystem.jca_demo.maxant.ch/", "BookingSystemPort"), BookingSystem.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookingSystem
     */
    @WebEndpoint(name = "BookingSystemPort")
    public BookingSystem getBookingSystemPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://bookingsystem.jca_demo.maxant.ch/", "BookingSystemPort"), BookingSystem.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKINGSYSTEMWEBSERVICESERVICE_EXCEPTION!= null) {
            throw BOOKINGSYSTEMWEBSERVICESERVICE_EXCEPTION;
        }
        return BOOKINGSYSTEMWEBSERVICESERVICE_WSDL_LOCATION;
    }

}
