
package ch.maxant.jca_demo.bookingsystem;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookingSystem", targetNamespace = "http://bookingsystem.jca_demo.maxant.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookingSystem {


    /**
     * 
     * @param referenceNumber
     * @param txid
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveTickets", targetNamespace = "http://bookingsystem.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.bookingsystem.ReserveTickets")
    @ResponseWrapper(localName = "reserveTicketsResponse", targetNamespace = "http://bookingsystem.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.bookingsystem.ReserveTicketsResponse")
    public String reserveTickets(
        @WebParam(name = "txid", targetNamespace = "")
        String txid,
        @WebParam(name = "referenceNumber", targetNamespace = "")
        String referenceNumber)
        throws Exception_Exception
    ;

    /**
     * 
     * @param txId
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "cancelTickets", targetNamespace = "http://bookingsystem.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.bookingsystem.CancelTickets")
    @ResponseWrapper(localName = "cancelTicketsResponse", targetNamespace = "http://bookingsystem.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.bookingsystem.CancelTicketsResponse")
    public void cancelTickets(
        @WebParam(name = "txId", targetNamespace = "")
        String txId)
        throws IOException_Exception
    ;

    /**
     * 
     * @param txId
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "bookTickets", targetNamespace = "http://bookingsystem.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.bookingsystem.BookTickets")
    @ResponseWrapper(localName = "bookTicketsResponse", targetNamespace = "http://bookingsystem.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.bookingsystem.BookTicketsResponse")
    public void bookTickets(
        @WebParam(name = "txId", targetNamespace = "")
        String txId)
        throws IOException_Exception
    ;

}
