
package ch.maxant.jca_demo.acquirer;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Acquirer", targetNamespace = "http://acquirer.jca_demo.maxant.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Acquirer {


    /**
     * 
     * @param txId
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "bookReservation", targetNamespace = "http://acquirer.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.acquirer.BookReservation")
    @ResponseWrapper(localName = "bookReservationResponse", targetNamespace = "http://acquirer.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.acquirer.BookReservationResponse")
    public void bookReservation(
        @WebParam(name = "txId", targetNamespace = "")
        String txId)
        throws IOException_Exception
    ;

    /**
     * 
     * @param txId
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "cancelReservation", targetNamespace = "http://acquirer.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.acquirer.CancelReservation")
    @ResponseWrapper(localName = "cancelReservationResponse", targetNamespace = "http://acquirer.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.acquirer.CancelReservationResponse")
    public void cancelReservation(
        @WebParam(name = "txId", targetNamespace = "")
        String txId)
        throws IOException_Exception
    ;

    /**
     * 
     * @param referenceNumber
     * @param txid
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "reserveMoney", targetNamespace = "http://acquirer.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.acquirer.ReserveMoney")
    @ResponseWrapper(localName = "reserveMoneyResponse", targetNamespace = "http://acquirer.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.acquirer.ReserveMoneyResponse")
    public String reserveMoney(
        @WebParam(name = "txid", targetNamespace = "")
        String txid,
        @WebParam(name = "referenceNumber", targetNamespace = "")
        String referenceNumber)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findUnfinishedTransactions", targetNamespace = "http://acquirer.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.acquirer.FindUnfinishedTransactions")
    @ResponseWrapper(localName = "findUnfinishedTransactionsResponse", targetNamespace = "http://acquirer.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.acquirer.FindUnfinishedTransactionsResponse")
    public List<String> findUnfinishedTransactions()
        throws IOException_Exception
    ;

}
