
package ch.maxant.jca_demo.letterwriter;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LetterWriter", targetNamespace = "http://letterwriter.jca_demo.maxant.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LetterWriter {


    /**
     * 
     * @param txId
     * @throws IOException_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "cancelLetter", targetNamespace = "http://letterwriter.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.letterwriter.CancelLetter")
    @ResponseWrapper(localName = "cancelLetterResponse", targetNamespace = "http://letterwriter.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.letterwriter.CancelLetterResponse")
    public void cancelLetter(
        @WebParam(name = "txId", targetNamespace = "")
        String txId)
        throws IOException_Exception
    ;

    /**
     * 
     * @param referenceNumber
     * @param txid
     * @return
     *     returns java.lang.String
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "writeLetter", targetNamespace = "http://letterwriter.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.letterwriter.WriteLetter")
    @ResponseWrapper(localName = "writeLetterResponse", targetNamespace = "http://letterwriter.jca_demo.maxant.ch/", className = "ch.maxant.jca_demo.letterwriter.WriteLetterResponse")
    public String writeLetter(
        @WebParam(name = "txid", targetNamespace = "")
        String txid,
        @WebParam(name = "referenceNumber", targetNamespace = "")
        String referenceNumber)
        throws Exception_Exception
    ;

}
